
FROM nvcr.io/nvidia/pytorch:24.02-py3

# Zmienne środowiskowe
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TOKENIZERS_PARALLELISM=false \
    HF_HOME=/models/.cache \
    TRANSFORMERS_CACHE=/models/.cache \
    PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128

WORKDIR /app

# Twoje zależności
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Kopiuj aplikację
COPY main.py /app/main.py

EXPOSE 8000

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000","--workers","1","--timeout-keep-alive","75"]
